=== oubtoumohamed/fml/data/matche.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="matche" type="complexroot">
        <xs:complexType>
            <xs:sequence>
                <!-- 
                    id : Identification of match
                    competition_id : id of competiton 
                    date & time : date time of match
                    status : state of match ( played, playing, planified )
                    winner : result of match ( team_a, team_b, draw )
                    stadium : place when be match play
                    team_a, team_b : ids of teams
                -->
                <xs:element name="id" type="xs:integer" maxOccurs="1"/>
                <xs:element name="competition_id" type="xs:integer" maxOccurs="1"/>
                <xs:element name="date" type="xs:date" maxOccurs="1"/>
                <xs:element name="time" type="xs:time" maxOccurs="1"/>
                <xs:element name="status">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:enumeration value="played"/>
                        <xs:enumeration value="playing"/>
                        <xs:enumeration value="planified"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <xs:element name="winner">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                        <xs:enumeration value="team_a"/>
                        <xs:enumeration value="team_b"/>
                        <xs:enumeration value="draw"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element> 
                <xs:element name="stadium" type="xs:string" maxOccurs="1"/>
                <xs:element name="team_a" type="xs:integer" maxOccurs="1"/>
                <xs:element name="team_b" type="xs:integer" maxOccurs="1"/>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== oubtoumohamed/fml/data/matches/17429/matche-3029246.xml
<?xml version="1.0" encoding="UTF-8"?> 

<matche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="matche.xsd"> 
   <id>3029246</id> 
   <competition_id>17429</competition_id> 
   <date>2019-12-21</date> 
   <time>12:30:00</time> 
   <status>Played</status> 
   <stadium></stadium> 
   <winner>draw</winner> 
 
   <team_a id="674" score="0" /> 
   <team_b id="660" score="0" /> 
</matche>

=== oubtoumohamed/fml/data/old--matches/17512/matche3047023.xml
<?xml version="1.0" encoding="UTF-8"?> 

<matche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="matche.xsd"> 
   <id>3047023</id> 
   <competition_id>17512</competition_id> 
   <date>2019-08-17</date> 
   <time>16:30:00</time> 
   <status>Played</status> 
   <winner>draw</winner> 
   <stadium></stadium> 
   <team_a id="971" /> 
   <team_b id="966" /> 
</matche>

=== oubtoumohamed/fml/data/matches/17886/matche-3111996.xml
<?xml version="1.0" encoding="UTF-8"?> 

<matche xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="matche.xsd"> 
   <id>3111996</id> 
   <competition_id>17886</competition_id> 
   <date>2020-04-05</date> 
   <time>18:45:00</time> 
   <status>Fixture</status> 
   <stadium></stadium> 
   <winner>yet unknown</winner> 
 
   <team_a id="1245" score="" /> 
   <team_b id="1240" score="" /> 
</matche>
