=== oubtoumohamed/fml/data/player.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="player" type="complexroot">
  <xs:complexType>
    <xs:sequence>

        <xs:element name="club" type="xs:integer" maxOccurs="1"/>
        <xs:element name="id" type="xs:integer" maxOccurs="1"/>
        <xs:element name="name" type="xs:string" maxOccurs="1"/>
        <xs:element name="image" type="xs:anyURI" maxOccurs="1"/>
        <xs:element name="position" type="xs:string" maxOccurs="1"/>
        <xs:element name="nationality" type="xs:string" maxOccurs="1"/>
        <xs:element name="birth-day" type="xs:date" maxOccurs="1"/>

        <xs:element name="length" type="xs:decimal"  maxOccurs="1">
            <xs:complexType>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:complexType>
		    </xs:element>
        <xs:element name="weight" type="xs:decimal"  maxOccurs="1">
            <xs:complexType>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:complexType>
		    </xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== oubtoumohamed/fml/data/players/player-441519.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>1205</team_id> 
   <id>441519</id> 
   <name>E. Zeka</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/441519.png</image> 
   <position>ألبانيا</position> 
   <nationality>Shkodër</nationality> 
   <birth-day>ألبانيا</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-534329.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>3565</team_id> 
   <id>534329</id> 
   <name>Mohammad Al Emwasi</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/534329.png</image> 
   <position>حارس مرمى</position> 
   <nationality>الأردن</nationality> 
   <birth-day>1996-08-08</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-164995.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>703</team_id> 
   <id>164995</id> 
   <name>خابيير غراسيا</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/164995.png</image> 
   <position>إسبانيا</position> 
   <nationality>1970-05-01</nationality> 
   <birth-day>Pamplona</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-212683.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>1250</team_id> 
   <id>212683</id> 
   <name>رولاندو ماران</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/212683.png</image> 
   <position>غير معروف</position> 
   <nationality>إيطاليا</nationality> 
   <birth-day>1963-07-14</birth-day> 
   <length  unit="cm">إيطاليا</length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-503328.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>11710</team_id> 
   <id>503328</id> 
   <name>M. Barman</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/503328.png</image> 
   <position>مهاجم</position> 
   <nationality>تركيا</nationality> 
   <birth-day>2000-05-28</birth-day> 
   <length  unit="cm">تركيا</length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-605708.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>178</team_id> 
   <id>605708</id> 
   <name>O. Starynskyi</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/605708.png</image> 
   <position>غير معروف</position> 
   <nationality>أوكرانيا</nationality> 
   <birth-day>1985-11-28</birth-day> 
   <length  unit="cm">أوكرانيا</length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-464122.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>207</team_id> 
   <id>464122</id> 
   <name>م. نغوم</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/464122.png</image> 
   <position>لاعب وسط</position> 
   <nationality>بلاروسيا</nationality> 
   <birth-day>1999-08-26</birth-day> 
   <length  unit="cm">بلاروسيا</length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-601262.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>327</team_id> 
   <id>601262</id> 
   <name>Diguinho</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/601262.png</image> 
   <position>مدافع</position> 
   <nationality>البرازيل</nationality> 
   <birth-day>2001-05-26</birth-day> 
   <length  unit="cm">البرازيل</length> 
   <weight  unit="kg"></weight> 
</player>
