=== oubtoumohamed/fml/data/player.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="player" type="complexroot">
  <xs:complexType>
    <xs:sequence>

        <xs:element name="club" type="xs:integer" maxOccurs="1"/>
        <xs:element name="id" type="xs:integer" maxOccurs="1"/>
        <xs:element name="name" type="xs:string" maxOccurs="1"/>
        <xs:element name="image" type="xs:anyURI" maxOccurs="1"/>
        <xs:element name="position" type="xs:string" maxOccurs="1"/>
        <xs:element name="nationality" type="xs:string" maxOccurs="1"/>
        <xs:element name="birth-day" type="xs:date" maxOccurs="1"/>

        <xs:element name="length" type="xs:decimal"  maxOccurs="1">
            <xs:complexType>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:complexType>
		    </xs:element>
        <xs:element name="weight" type="xs:decimal"  maxOccurs="1">
            <xs:complexType>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:complexType>
		    </xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== oubtoumohamed/fml/data/players/player-108526.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>1568</team_id> 
   <id>108526</id> 
   <name>نيكولا راكوجيفتش</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/108526.png</image> 
   <position>مونتينيغرو</position> 
   <nationality>1958-01-15</nationality> 
   <birth-day>مونتينيغرو</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-566867.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>601</team_id> 
   <id>566867</id> 
   <name>J. Lindstrøm</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/566867.png</image> 
   <position>لاعب وسط</position> 
   <nationality>الدنمارك</nationality> 
   <birth-day>2000-02-29</birth-day> 
   <length  unit="cm">181</length> 
   <weight  unit="kg">63</weight> 
</player>

=== oubtoumohamed/fml/data/players/player-509305.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>10610</team_id> 
   <id>509305</id> 
   <name>N. Sergeev</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/509305.png</image> 
   <position>مهاجم</position> 
   <nationality>روسيا</nationality> 
   <birth-day>1999-10-17</birth-day> 
   <length  unit="cm">روسيا</length> 
   <weight  unit="kg">176</weight> 
</player>

=== oubtoumohamed/fml/data/players/player-642328.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>5026</team_id> 
   <id>642328</id> 
   <name>Y. Saidi</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/642328.png</image> 
   <position>حارس مرمى</position> 
   <nationality>تونس</nationality> 
   <birth-day>1998-01-08</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-480013.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>548</team_id> 
   <id>480013</id> 
   <name>P. Mikulec</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/480013.png</image> 
   <position>حارس مرمى</position> 
   <nationality>التشيك</nationality> 
   <birth-day>1999-04-05</birth-day> 
   <length  unit="cm">التشيك</length> 
   <weight  unit="kg">197</weight> 
</player>

=== oubtoumohamed/fml/data/players/player-588788.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>22136</team_id> 
   <id>588788</id> 
   <name>Y. Fertout</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/588788.png</image> 
   <position>غير معروف</position> 
   <nationality>المغرب</nationality> 
   <birth-day>1970-07-07</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-644818.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>2331</team_id> 
   <id>644818</id> 
   <name>L. Garrett</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/644818.png</image> 
   <position>مدافع</position> 
   <nationality>ويلز</nationality> 
   <birth-day>ويلز</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-626378.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>1240</team_id> 
   <id>626378</id> 
   <name>أليساندرو سالا</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/626378.png</image> 
   <position>لاعب وسط</position> 
   <nationality>إيطاليا</nationality> 
   <birth-day>2001-05-07</birth-day> 
   <length  unit="cm">إيطاليا</length> 
   <weight  unit="kg">185</weight> 
</player>
