=== oubtoumohamed/fml/data/player.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="player" type="complexroot">
  <xs:complexType>
    <xs:sequence>

        <xs:element name="club" type="xs:integer" maxOccurs="1"/>
        <xs:element name="id" type="xs:integer" maxOccurs="1"/>
        <xs:element name="name" type="xs:string" maxOccurs="1"/>
        <xs:element name="image" type="xs:anyURI" maxOccurs="1"/>
        <xs:element name="position" type="xs:string" maxOccurs="1"/>
        <xs:element name="nationality" type="xs:string" maxOccurs="1"/>
        <xs:element name="birth-day" type="xs:date" maxOccurs="1"/>

        <xs:element name="length" type="xs:decimal"  maxOccurs="1">
            <xs:complexType>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:complexType>
		    </xs:element>
        <xs:element name="weight" type="xs:decimal"  maxOccurs="1">
            <xs:complexType>
                <xs:attribute name="unit" type="xs:string"/>
            </xs:complexType>
		    </xs:element>

    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== oubtoumohamed/fml/data/players/player-509013.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>12387</team_id> 
   <id>509013</id> 
   <name>V. Naydenov</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/509013.png</image> 
   <position>مهاجم</position> 
   <nationality>بلغاريا</nationality> 
   <birth-day>2001-11-29</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-634192.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>5555</team_id> 
   <id>634192</id> 
   <name>S. Barrouhou</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/634192.png</image> 
   <position>حارس مرمى</position> 
   <nationality>المغرب</nationality> 
   <birth-day>1994-01-18</birth-day> 
   <length  unit="cm">191</length> 
   <weight  unit="kg">78</weight> 
</player>

=== oubtoumohamed/fml/data/players/player-637968.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>1184</team_id> 
   <id>637968</id> 
   <name>D. Bogdanov</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/637968.png</image> 
   <position>مهاجم</position> 
   <nationality>أيرلندا</nationality> 
   <birth-day>أيرلندا</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-612615.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>1245</team_id> 
   <id>612615</id> 
   <name>A. Bianchi</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/612615.png</image> 
   <position>لاعب وسط</position> 
   <nationality>إيطاليا</nationality> 
   <birth-day>2000-10-02</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-373521.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>11710</team_id> 
   <id>373521</id> 
   <name>إيجور تشيريفشينكو</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/373521.png</image> 
   <position>مدافع</position> 
   <nationality>طاجكستان</nationality> 
   <birth-day>1974-08-21</birth-day> 
   <length  unit="cm">طاجكستان</length> 
   <weight  unit="kg">178</weight> 
</player>

=== oubtoumohamed/fml/data/players/player-555189.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>6676</team_id> 
   <id>555189</id> 
   <name>A. Kouadio</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/555189.png</image> 
   <position>مهاجم</position> 
   <nationality>ساحل العاج</nationality> 
   <birth-day>1996-05-19</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-451913.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>778</team_id> 
   <id>451913</id> 
   <name>J. Hauksson</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/451913.png</image> 
   <position>غير معروف</position> 
   <nationality>أيسلندا</nationality> 
   <birth-day>أيسلندا</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>

=== oubtoumohamed/fml/data/players/player-616493.xml
<?xml version="1.0" encoding="UTF-8"?> 

<player xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="player.xsd"> 
   <team_id>3231</team_id> 
   <id>616493</id> 
   <name>A. Ćatović</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/players/150x150/616493.png</image> 
   <position>مدافع</position> 
   <nationality>مونتينيغرو</nationality> 
   <birth-day>2001-06-10</birth-day> 
   <length  unit="cm"></length> 
   <weight  unit="kg"></weight> 
</player>
