=== oubtoumohamed/fml/data/team.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="team" type="complexroot">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:integer" maxOccurs="1"/>
                <xs:element name="name" type="xs:string" maxOccurs="1"/>
                <xs:element name="image" type="xs:string" maxOccurs="1"/>
                <xs:element name="country" type="xs:string" maxOccurs="1"/>
                <xs:element name="adrese" type="xs:string" maxOccurs="1"/>
                <xs:element name="website" type="xs:anyURI" maxOccurs="1"/>
                <xs:element name="creation-date" type="xs:date" maxOccurs="1"/>

                <xs:element name="players" type="complexPlayers" minOccurs="unbounded"/>
                <xs:element name="coaches" type="complexCoaches" minOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="complexPlayers">
        <xs:sequence>
            <xs:element name="player">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:integer"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="complexCoaches">
        <xs:sequence>
            <xs:element name="coach">
                <xs:complexType>
                    <xs:sequence>

                        <xs:element name="id" type="xs:integer" maxOccurs="1"/>
                        <xs:element name="name" type="xs:string" maxOccurs="1"/>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== oubtoumohamed/fml/data/teams/team-3418.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>3418</id> 
   <name>نادي شبيبة القبائل</name> 
   <image>https://s1.hesport.com/themes/desktop/img/teams/3418.png</image> 
   <country>الجزائر</country> 
   <adrese>Stade du 1er Novembre 1954</adrese> 
   <website>http://www.jeunessesportivedekabylie.com/</website> 
   <creation-date>1946</creation-date> 
   <players> 
     <player id="49108" /> 
     <player id="49132" /> 
     <player id="312110" /> 
     <player id="455173" /> 
     <player id="501758" /> 
     <player id="621073" /> 
     <player id="645414" /> 
     <player id="647539" /> 
     <player id="89335" /> 
     <player id="178609" /> 
     <player id="263487" /> 
     <player id="264054" /> 
     <player id="266643" /> 
     <player id="322708" /> 
     <player id="360357" /> 
     <player id="414108" /> 
     <player id="421933" /> 
     <player id="431452" /> 
     <player id="455156" /> 
     <player id="470672" /> 
     <player id="470673" /> 
     <player id="495326" /> 
     <player id="495328" /> 
     <player id="495331" /> 
     <player id="555720" /> 
     <player id="555721" /> 
     <player id="555728" /> 
     <player id="555729" /> 
     <player id="585112" /> 
     <player id="630110" /> 
     <player id="64553" /> 
     <player id="103095" /> 
     <player id="103793" /> 
     <player id="164027" /> 
     <player id="191276" /> 
     <player id="245203" /> 
     <player id="256487" /> 
     <player id="265340" /> 
     <player id="331272" /> 
     <player id="358633" /> 
     <player id="432211" /> 
     <player id="438593" /> 
     <player id="443874" /> 
     <player id="467528" /> 
     <player id="479151" /> 
     <player id="495306" /> 
     <player id="495333" /> 
     <player id="495334" /> 
     <player id="496055" /> 
     <player id="501761" /> 
     <player id="556756" /> 
     <player id="585111" /> 
     <player id="621078" /> 
     <player id="647176" /> 
     <player id="648336" /> 
     <player id="183199" /> 
     <player id="192679" /> 
     <player id="262302" /> 
     <player id="281753" /> 
     <player id="309951" /> 
     <player id="359729" /> 
     <player id="401717" /> 
     <player id="428973" /> 
     <player id="430650" /> 
     <player id="431448" /> 
     <player id="468256" /> 
     <player id="470294" /> 
     <player id="513309" /> 
     <player id="555727" /> 
     <player id="585110" /> 
     <player id="604968" /> 
   </players> 
   <coaches> 
     <coach id="49022" /> 
     <coach id="111200" /> 
     <coach id="138182" /> 
     <coach id="210744" /> 
     <coach id="304814" /> 
     <coach id="393661" /> 
     <coach id="403968" /> 
     <coach id="434798" /> 
     <coach id="440747" /> 
     <coach id="467109" /> 
     <coach id="541967" /> 
     <coach id="593876" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-3511.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>3511</id> 
   <name>الهلال</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/3511.png</image> 
   <country>السعودية</country> 
   <adrese></adrese> 
   <website>http://www.alhilal.com</website> 
   <creation-date>1957</creation-date> 
   <players> 
     <player id="10872" /> 
     <player id="26594" /> 
     <player id="309813" /> 
     <player id="436615" /> 
     <player id="576449" /> 
     <player id="640019" /> 
     <player id="10934" /> 
     <player id="62738" /> 
     <player id="81513" /> 
     <player id="121459" /> 
     <player id="144187" /> 
     <player id="164599" /> 
     <player id="193362" /> 
     <player id="197689" /> 
     <player id="197874" /> 
     <player id="207472" /> 
     <player id="255776" /> 
     <player id="263793" /> 
     <player id="326126" /> 
     <player id="326952" /> 
     <player id="397041" /> 
     <player id="414800" /> 
     <player id="452466" /> 
     <player id="465465" /> 
     <player id="492142" /> 
     <player id="10944" /> 
     <player id="64099" /> 
     <player id="66928" /> 
     <player id="71055" /> 
     <player id="84154" /> 
     <player id="110254" /> 
     <player id="110805" /> 
     <player id="124453" /> 
     <player id="128583" /> 
     <player id="156094" /> 
     <player id="179101" /> 
     <player id="197872" /> 
     <player id="197881" /> 
     <player id="280637" /> 
     <player id="316240" /> 
     <player id="323061" /> 
     <player id="465476" /> 
     <player id="492141" /> 
     <player id="492155" /> 
     <player id="529352" /> 
     <player id="576469" /> 
     <player id="590767" /> 
     <player id="590768" /> 
     <player id="1331" /> 
     <player id="3646" /> 
     <player id="10955" /> 
     <player id="17951" /> 
     <player id="81456" /> 
     <player id="87684" /> 
     <player id="131571" /> 
     <player id="180819" /> 
     <player id="217887" /> 
     <player id="234061" /> 
     <player id="405642" /> 
     <player id="465482" /> 
     <player id="470973" /> 
     <player id="484481" /> 
     <player id="492145" /> 
     <player id="576456" /> 
     <player id="598567" /> 
     <player id="600752" /> 
   </players> 
   <coaches> 
     <coach id="48213" /> 
     <coach id="125542" /> 
     <coach id="127143" /> 
     <coach id="140283" /> 
     <coach id="230964" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-236.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>236</id> 
   <name>نادي زولته فارجيم الرياضي</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/236.png</image> 
   <country>بلجيكا</country> 
   <adrese>Zuiderlaan 17</adrese> 
   <website>http://www.essevee.be</website> 
   <creation-date>2001</creation-date> 
   <players> 
     <player id="13536" /> 
     <player id="145427" /> 
     <player id="310459" /> 
     <player id="2257" /> 
     <player id="2431" /> 
     <player id="4588" /> 
     <player id="20675" /> 
     <player id="28243" /> 
     <player id="111434" /> 
     <player id="197625" /> 
     <player id="205603" /> 
     <player id="205722" /> 
     <player id="245613" /> 
     <player id="257296" /> 
     <player id="298166" /> 
     <player id="376291" /> 
     <player id="393500" /> 
     <player id="435960" /> 
     <player id="443145" /> 
     <player id="477613" /> 
     <player id="597627" /> 
     <player id="827" /> 
     <player id="2136" /> 
     <player id="12923" /> 
     <player id="13427" /> 
     <player id="13668" /> 
     <player id="37761" /> 
     <player id="138277" /> 
     <player id="158657" /> 
     <player id="183119" /> 
     <player id="231672" /> 
     <player id="245105" /> 
     <player id="255123" /> 
     <player id="267149" /> 
     <player id="274253" /> 
     <player id="289439" /> 
     <player id="296548" /> 
     <player id="297272" /> 
     <player id="385473" /> 
     <player id="395070" /> 
     <player id="402769" /> 
     <player id="408766" /> 
     <player id="429607" /> 
     <player id="448395" /> 
     <player id="460054" /> 
     <player id="572571" /> 
     <player id="578630" /> 
     <player id="9933" /> 
     <player id="21128" /> 
     <player id="87636" /> 
     <player id="134184" /> 
     <player id="149485" /> 
     <player id="189983" /> 
     <player id="232999" /> 
     <player id="283151" /> 
     <player id="302900" /> 
     <player id="314099" /> 
     <player id="317305" /> 
     <player id="319030" /> 
     <player id="335079" /> 
     <player id="342717" /> 
     <player id="579448" /> 
   </players> 
   <coaches> 
     <coach id="114537" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-3513.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>3513</id> 
   <name>الإتحاد</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/3513.png</image> 
   <country>السعودية</country> 
   <adrese>Sahafa Street</adrese> 
   <website>http://www.ittihadnet.net</website> 
   <creation-date>1927</creation-date> 
   <players> 
     <player id="9187" /> 
     <player id="143679" /> 
     <player id="197883" /> 
     <player id="222651" /> 
     <player id="358691" /> 
     <player id="415450" /> 
     <player id="472770" /> 
     <player id="466" /> 
     <player id="2388" /> 
     <player id="26438" /> 
     <player id="61225" /> 
     <player id="65339" /> 
     <player id="66884" /> 
     <player id="66932" /> 
     <player id="69569" /> 
     <player id="143732" /> 
     <player id="144203" /> 
     <player id="144237" /> 
     <player id="190157" /> 
     <player id="222814" /> 
     <player id="295040" /> 
     <player id="295569" /> 
     <player id="309671" /> 
     <player id="320424" /> 
     <player id="326949" /> 
     <player id="327605" /> 
     <player id="333848" /> 
     <player id="334006" /> 
     <player id="371317" /> 
     <player id="403451" /> 
     <player id="419725" /> 
     <player id="465460" /> 
     <player id="474257" /> 
     <player id="474843" /> 
     <player id="494918" /> 
     <player id="520284" /> 
     <player id="576450" /> 
     <player id="647628" /> 
     <player id="2466" /> 
     <player id="8246" /> 
     <player id="10439" /> 
     <player id="68553" /> 
     <player id="76643" /> 
     <player id="131367" /> 
     <player id="150612" /> 
     <player id="167547" /> 
     <player id="175393" /> 
     <player id="207636" /> 
     <player id="233411" /> 
     <player id="245782" /> 
     <player id="316232" /> 
     <player id="317939" /> 
     <player id="371355" /> 
     <player id="414887" /> 
     <player id="435182" /> 
     <player id="465783" /> 
     <player id="465886" /> 
     <player id="482591" /> 
     <player id="527782" /> 
     <player id="529353" /> 
     <player id="544999" /> 
     <player id="576472" /> 
     <player id="598557" /> 
     <player id="644916" /> 
     <player id="31558" /> 
     <player id="59705" /> 
     <player id="61394" /> 
     <player id="67634" /> 
     <player id="71412" /> 
     <player id="88907" /> 
     <player id="112373" /> 
     <player id="158613" /> 
     <player id="197876" /> 
     <player id="211905" /> 
     <player id="228967" /> 
     <player id="282741" /> 
     <player id="375315" /> 
     <player id="455531" /> 
     <player id="472773" /> 
     <player id="538177" /> 
     <player id="590736" /> 
   </players> 
   <coaches> 
     <coach id="104690" /> 
     <coach id="119288" /> 
     <coach id="157287" /> 
     <coach id="169469" /> 
     <coach id="482592" /> 
     <coach id="641701" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-9133.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>9133</id> 
   <name>نادي ميلسامي أورسيدوس أوري لكرة القدم</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/9133.png</image> 
   <country>مولدوفا</country> 
   <adrese>Str. Grozescu, nr. 91A</adrese> 
   <website>http://www.milsami.md</website> 
   <creation-date>2005</creation-date> 
   <players> 
     <player id="38922" /> 
     <player id="296165" /> 
     <player id="297926" /> 
     <player id="427807" /> 
     <player id="427808" /> 
     <player id="39482" /> 
     <player id="122072" /> 
     <player id="122667" /> 
     <player id="217617" /> 
     <player id="269981" /> 
     <player id="272393" /> 
     <player id="281043" /> 
     <player id="312323" /> 
     <player id="423820" /> 
     <player id="605705" /> 
     <player id="616213" /> 
     <player id="616214" /> 
     <player id="38912" /> 
     <player id="38924" /> 
     <player id="39495" /> 
     <player id="76700" /> 
     <player id="83017" /> 
     <player id="83390" /> 
     <player id="138902" /> 
     <player id="262293" /> 
     <player id="298614" /> 
     <player id="335701" /> 
     <player id="423825" /> 
     <player id="446192" /> 
     <player id="563800" /> 
     <player id="586273" /> 
     <player id="635746" /> 
     <player id="12040" /> 
     <player id="38911" /> 
     <player id="38913" /> 
     <player id="59591" /> 
     <player id="163584" /> 
     <player id="315823" /> 
     <player id="384531" /> 
     <player id="397079" /> 
     <player id="445642" /> 
     <player id="452712" /> 
     <player id="463296" /> 
   </players> 
   <coaches> 
     <coach id="198456" /> 
     <coach id="335178" /> 
     <coach id="393128" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-890.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>890</id> 
   <name>أولمبيك مارسيليا</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/890.png</image> 
   <country>فرنسا</country> 
   <adrese>La Commanderie, 33, traverse de La Martine</adrese> 
   <website>http://www.om.net</website> 
   <creation-date>1899</creation-date> 
   <players> 
     <player id="1227" /> 
     <player id="13106" /> 
     <player id="264407" /> 
     <player id="320099" /> 
     <player id="446018" /> 
     <player id="627718" /> 
     <player id="13635" /> 
     <player id="16625" /> 
     <player id="26192" /> 
     <player id="47038" /> 
     <player id="53329" /> 
     <player id="74373" /> 
     <player id="177262" /> 
     <player id="183963" /> 
     <player id="217615" /> 
     <player id="227884" /> 
     <player id="247931" /> 
     <player id="266051" /> 
     <player id="426522" /> 
     <player id="429737" /> 
     <player id="436464" /> 
     <player id="454974" /> 
     <player id="529690" /> 
     <player id="1394" /> 
     <player id="10592" /> 
     <player id="24675" /> 
     <player id="75257" /> 
     <player id="87812" /> 
     <player id="180836" /> 
     <player id="180846" /> 
     <player id="242484" /> 
     <player id="269516" /> 
     <player id="292940" /> 
     <player id="309764" /> 
     <player id="314574" /> 
     <player id="394835" /> 
     <player id="479198" /> 
     <player id="519888" /> 
     <player id="564643" /> 
     <player id="19125" /> 
     <player id="22357" /> 
     <player id="68165" /> 
     <player id="159224" /> 
     <player id="217869" /> 
     <player id="416502" /> 
     <player id="472072" /> 
     <player id="601234" /> 
   </players> 
   <coaches> 
     <coach id="110849" /> 
     <coach id="140282" /> 
     <coach id="304630" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-353.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>353</id> 
   <name>نادي ليفسكي صوفيا</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/353.png</image> 
   <country>بلغاريا</country> 
   <adrese>ul. Todorini Kukli 47</adrese> 
   <website>http://www.levski.bg</website> 
   <creation-date>1914</creation-date> 
   <players> 
     <player id="13575" /> 
     <player id="16069" /> 
     <player id="51701" /> 
     <player id="92026" /> 
     <player id="135417" /> 
     <player id="235205" /> 
     <player id="273939" /> 
     <player id="404397" /> 
     <player id="463271" /> 
     <player id="4618" /> 
     <player id="9846" /> 
     <player id="46337" /> 
     <player id="80583" /> 
     <player id="134611" /> 
     <player id="182400" /> 
     <player id="183915" /> 
     <player id="185245" /> 
     <player id="215644" /> 
     <player id="257317" /> 
     <player id="270099" /> 
     <player id="319423" /> 
     <player id="322289" /> 
     <player id="515348" /> 
     <player id="2992" /> 
     <player id="8817" /> 
     <player id="39872" /> 
     <player id="84311" /> 
     <player id="84314" /> 
     <player id="160127" /> 
     <player id="163091" /> 
     <player id="201982" /> 
     <player id="210779" /> 
     <player id="214885" /> 
     <player id="228701" /> 
     <player id="235774" /> 
     <player id="254290" /> 
     <player id="261627" /> 
     <player id="262476" /> 
     <player id="263928" /> 
     <player id="271920" /> 
     <player id="275122" /> 
     <player id="404404" /> 
     <player id="404406" /> 
     <player id="404408" /> 
     <player id="449297" /> 
     <player id="463291" /> 
     <player id="463758" /> 
     <player id="515368" /> 
     <player id="16068" /> 
     <player id="35588" /> 
     <player id="134081" /> 
     <player id="141191" /> 
     <player id="156117" /> 
     <player id="247995" /> 
     <player id="273946" /> 
     <player id="284555" /> 
     <player id="328118" /> 
     <player id="377383" /> 
     <player id="385287" /> 
     <player id="414319" /> 
     <player id="426831" /> 
     <player id="465901" /> 
     <player id="555914" /> 
     <player id="605622" /> 
     <player id="612463" /> 
   </players> 
   <coaches> 
     <coach id="51745" /> 
     <coach id="110812" /> 
     <coach id="140447" /> 
     <coach id="201985" /> 
     <coach id="215027" /> 
     <coach id="302332" /> 
     <coach id="354015" /> 
   </coaches> 
</team>

=== oubtoumohamed/fml/data/teams/team-39594.xml
<?xml version="1.0" encoding="UTF-8"?> 

<team xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="team.xsd"> 
   <id>39594</id> 
   <name>Ararat-Armenia FC</name> 
   <image>https://secure.cache.images.core.optasports.com/soccer/teams/150x150/39594.png</image> 
   <country>أرمينيا</country> 
   <adrese></adrese> 
   <website></website> 
   <creation-date></creation-date> 
   <players> 
     <player id="76328" /> 
     <player id="291882" /> 
     <player id="320286" /> 
     <player id="468823" /> 
     <player id="619159" /> 
     <player id="6627" /> 
     <player id="59348" /> 
     <player id="124565" /> 
     <player id="263848" /> 
     <player id="313142" /> 
     <player id="314309" /> 
     <player id="320294" /> 
     <player id="384585" /> 
     <player id="400329" /> 
     <player id="441619" /> 
     <player id="482403" /> 
     <player id="124586" /> 
     <player id="129065" /> 
     <player id="155435" /> 
     <player id="160145" /> 
     <player id="169938" /> 
     <player id="180108" /> 
     <player id="263647" /> 
     <player id="384593" /> 
     <player id="385885" /> 
     <player id="423318" /> 
     <player id="448091" /> 
     <player id="450316" /> 
     <player id="460377" /> 
     <player id="507813" /> 
     <player id="27676" /> 
     <player id="40565" /> 
     <player id="51696" /> 
     <player id="59082" /> 
     <player id="102559" /> 
     <player id="131644" /> 
     <player id="331172" /> 
     <player id="384599" /> 
     <player id="425156" /> 
     <player id="449680" /> 
     <player id="468295" /> 
     <player id="579241" /> 
   </players> 
   <coaches> 
     <coach id="78281" /> 
     <coach id="135622" /> 
   </coaches> 
</team>
